version: '3'

networks:
  web:
    external: true

services:
  raincloud-api:
    image: $DOCKER_IMAGE
    environment:
      APP_NAME: $APP_NAME
      SERVER_PORT: $SERVER_PORT
      LOGGER_ENABLED: $LOGGER_ENABLED
      LOGGER_LEVEL: $LOGGER_LEVEL
      SC_CLIENT_ID: $SC_CLIENT_ID
      SC_CLIENT_SECRET: $SC_CLIENT_SECRET
      SC_REDIRECT_URI: $SC_REDIRECT_URI
    labels:
      - traefik.http.routers.raincloud-api.rule=Host(`${TRAEFIK_HOST}`)
      - traefik.http.routers.raincloud-api.tls=true
      - traefik.http.routers.raincloud-api.tls.certresolver=lets-encrypt
      - traefik.port=80
      - traefik.http.services.raincloud-api.loadbalancer.server.port=${SERVER_PORT}
    networks:
      - web
